package com.myxllite.app.kit.constant

/**
 * Created by Bacharudin Farisi on 29/03/22
 */
object CacheConstant {
    const val SHARED_PREFERENCE_NAME = "XL_ULTIMATE_CACHE"
    const val SHARED_PREFERENCE_NAME_UNCLEARABLE = "XL_ULTIMATE_CACHE_UNCLEARABLE"
    const val SHARED_PREFERENCE_NAME_NETWORK = "XL_ULTIMATE_CACHE_NETWORK"
    const val SHARED_PREFERENCE_NAME_CACHE_FAIL_SAFE = "XL_ULTIMATE_CACHE_FAIL_SAFE"
    const val SHARED_PREFERENCE_NAME_USER_SESSION = "XL_ULTIMATE_CACHE_USER_SESSION"
}